FROM node:10

# Create app directory
WORKDIR /www

# Install app dependencies
# RUN npm install -g npm
# RUN npm rebuild node-sass

COPY package.json package-lock.json ./
COPY src/modules ./src/modules
RUN npm install

COPY . /www
CMD [ "npm", "start" ]
