FROM node:10
 
# Create app directory
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
 
# Install app dependencies
COPY . /usr/src/app/
RUN npm install -g npm
RUN npm rebuild node-sass
RUN npm install
 
CMD [ "npm", "start" ]
