module.exports = {
  sections: [
    {
      name: 'Components',
      components: [
        'src/modules/zconnect-web/components/Address/index.js',
        'src/modules/zconnect-web/components/Button/index.js',
        'src/modules/zconnect-web/components/Card/index.js',
        'src/modules/zconnect-web/components/CheckboxForm/index.js',
        'src/modules/zconnect-web/components/Codeblock/index.js',
        'src/modules/zconnect-web/components/Content/index.js',
        'src/modules/zconnect-web/components/DateRangeModal/index.js',
        'src/modules/zconnect-web/components/DateRangePicker/index.js',
        'src/modules/zconnect-web/components/Drawer/index.js',
        'src/modules/zconnect-web/components/forms/CheckboxField/index.js',
        'src/modules/zconnect-web/components/forms/DateField/index.js',
        'src/modules/zconnect-web/components/forms/EmailField/index.js',
        'src/modules/zconnect-web/components/forms/PasswordField/index.js',
        'src/modules/zconnect-web/components/forms/SelectField/index.js',
        'src/modules/zconnect-web/components/forms/TextField/index.js',
        'src/modules/zconnect-web/components/Header/index.js',
        'src/modules/zconnect-web/components/Icon/index.js',
        'src/modules/zconnect-web/components/Link/index.js',
        'src/modules/zconnect-web/components/List/index.js',
        'src/modules/zconnect-web/components/Logo/index.js',
        'src/modules/zconnect-web/components/GoogleMap/index.js',
        'src/modules/zconnect-web/components/GoogleMap/Marker.js',
        'src/modules/zconnect-web/components/Message/index.js',
        'src/modules/zconnect-web/components/Modal/Modal.js',
        'src/modules/zconnect-web/components/Modal/ModalContainer.js',
        'src/modules/zconnect-web/components/NavButton/index.js',
        'src/modules/zconnect-web/components/Page/index.js',
        'src/modules/zconnect-web/components/Pagination/index.js',
        'src/modules/zconnect-web/components/Panel/index.js',
        'src/modules/zconnect-web/components/ProgressChart/index.js',
        'src/modules/zconnect-web/components/Spinner/index.js',
        'src/modules/zconnect-web/components/StatCard/index.js',
        'src/modules/zconnect-web/components/Tabs/index.js',
        'src/modules/zconnect-web/components/Tooltip/index.js',
        'src/modules/zconnect-web/components/ZCGriddle/index.js',
        'src/modules/zconnect-web/components/DrawerToggle.js',
      ],
    },
    {
      name: 'Containers',
      components: [
        'src/modules/zconnect-web/containers/ActivityStream/index.js',
        'src/modules/zconnect-web/containers/AsyncList/index.js',
        'src/modules/zconnect-web/containers/AsyncListWithState/index.js',
        /* I can't seem to get these components to render in the docs... */
        // 'src/modules/zconnect-web/containers/auth/Forgotten/index.js',
        // 'src/modules/zconnect-web/containers/auth/Login/index.js',
        // 'src/modules/zconnect-web/containers/auth/PasswordConfirm/index.js',
        // 'src/modules/zconnect-web/containers/auth/Register/index.js',
        'src/modules/zconnect-web/containers/Navbar/index.js',
        'src/modules/zconnect-web/containers/NotificationSettings/index.js',
        'src/modules/zconnect-web/containers/TimeSeriesGraph/index.js',
        'src/modules/zconnect-web/containers/TimeSeriesGraphPanel/index.js',
      ],
    },
  ],
}
