apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}-ingress
  labels:
    app: {{ template "name" . }}-ingress
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
  {{ $hostBackend := required "Need a host backend defined in 'ingress' values" .Values.ingress.host_backend | quote }}
  {{ if not .Values.STUPID_NO_TLS }}
  - hosts:
    - {{ $hostBackend }}
    secretName: {{ template "fullname" . }}-tls
  {{ end }}
  rules:
    - host: {{ $hostBackend }}
      http:
        paths:
      {{ $releaseName := .Release.Name }}
      {{ $fullName := include "fullname" . }}
      {{- range .Values.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $fullName }}-api
            servicePort: 80
      {{- end }}
